### ISSUE TITLE
run demo.py error

### ISSUE THREAD

**Issue by Gracccce** [VinAIResearch/dict-guided#11]
When I run this commmand:
`python demo/demo.py --config-file configs/BAText/VinText/attn_R_50.yaml --input sample_input/ --output sample_output/ --opts MODEL.WEIGHTS ./trained_model.pth`
**A error occured**
Traceback (most recent call last):
  File "demo/demo.py", line 10, in <module>
    from adet.config import get_cfg
  File "/usr/lml/dict-guided-main/adet/__init__.py", line 1, in <module>
    from adet import modeling
  File "/usr/lml/dict-guided-main/adet/modeling/__init__.py", line 2, in <module>
    from .backbone import build_fcos_resnet_fpn_backbone
  File "/usr/lml/dict-guided-main/adet/modeling/backbone/__init__.py", line 1, in <module>
    from .dla import build_fcos_dla_fpn_backbone
  File "/usr/lml/dict-guided-main/adet/modeling/backbone/dla.py", line 13, in <module>
    from detectron2.layers import ShapeSpec
  File "/root/anaconda3/envs/dict-guided/lib/python3.7/site-packages/detectron2/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/root/anaconda3/envs/dict-guided/lib/python3.7/site-packages/detectron2/layers/deform_conv.py", line 10, in <module>
    from detectron2 import _C
ImportError: /root/anaconda3/envs/dict-guided/lib/python3.7/site-packages/detectron2/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: THPVariableClass
I am wondering how to debug?

**Comment by LualuOntheSea** [comment]
> 

I met the same problem. Have you solved it?

**Comment by Gracccce** [comment]
Yes, but sorry, i do not remember how i solved it.

**Comment by LualuOntheSea** [comment]
That's all right. Anyway, thank u
----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："Gracccce ***@***.***&gt;;
发送时间：2022年3月13日(星期天) 晚上9:13
收件人："VinAIResearch/dict-guided" ***@***.***&gt;;
抄送："杨述敏 ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [VinAIResearch/dict-guided] run demo.py error (Issue #11)
-----------------------------------

 

 
Yes, but sorry, i do not remember how i solved it.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
