### ISSUE TITLE
Predict on CPU

### ISSUE THREAD

**Issue by lynguyenminh** [VinAIResearch/dict-guided#15]
Hi, 
I am presently utilizing this repository to anticipate the text's location. However, an error occurs when I attempt to predict on the CPU because I do not have a GPU.

[02/18 23:18:40 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='configs/BAText/VinText/attn_R_50.yaml', input=['sample_input/'], opts=['MODEL.WEIGHTS', 'model_0033999.pth'], output='sample_output/', video_input=None, webcam=False)
WARNING [02/18 23:18:40 d2.config.compat]: Config 'configs/BAText/VinText/attn_R_50.yaml' has no VERSION. Assuming it to be compatible with latest v2.
Traceback (most recent call last):
  File "demo/demo.py", line 74, in <module>
    demo = VisualizationDemo(cfg)
  File "/home/lynguyenminh/Workspace/Projects/dict-guided/dict-guided/demo/predictor.py", line 36, in __init__
    self.predictor = DefaultPredictor(cfg)
  File "/home/lynguyenminh/Workspace/Projects/dict-guided/venv/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 282, in __init__
    self.model = build_model(self.cfg)
  File "/home/lynguyenminh/Workspace/Projects/dict-guided/venv/lib/python3.8/site-packages/detectron2/modeling/meta_arch/build.py", line 23, in build_model
    model.to(torch.device(cfg.MODEL.DEVICE))
  File "/home/lynguyenminh/Workspace/Projects/dict-guided/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 899, in to
    return self._apply(convert)
  File "/home/lynguyenminh/Workspace/Projects/dict-guided/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  File "/home/lynguyenminh/Workspace/Projects/dict-guided/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  File "/home/lynguyenminh/Workspace/Projects/dict-guided/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 593, in _apply
    param_applied = fn(param)
  File "/home/lynguyenminh/Workspace/Projects/dict-guided/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 897, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/lynguyenminh/Workspace/Projects/dict-guided/venv/lib/python3.8/site-packages/torch/cuda/__init__.py", line 214, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

Is it support prediction in CPU?

**Comment by doanthuyennt** [comment]
Hello @lynguyenminh, I think your problem is related to #5.
