### ISSUE TITLE
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by thongvhoang** [VinAIResearch/dict-guided#4]
```
Using /usr/local/envs/dict-guided/lib/python3.7/site-packages
Finished processing dependencies for AdelaiDet==0.2.0
Traceback (most recent call last):
  File "demo/demo.py", line 10, in <module>
    from adet.config import get_cfg
  File "/usr/local/envs/dict-guided/lib/python3.7/site-packages/AdelaiDet-0.2.0-py3.7-linux-x86_64.egg/adet/__init__.py", line 1, in <module>
    from adet import modeling
  File "/usr/local/envs/dict-guided/lib/python3.7/site-packages/AdelaiDet-0.2.0-py3.7-linux-x86_64.egg/adet/modeling/__init__.py", line 3, in <module>
    from .batext import BAText
  File "/usr/local/envs/dict-guided/lib/python3.7/site-packages/AdelaiDet-0.2.0-py3.7-linux-x86_64.egg/adet/modeling/batext/__init__.py", line 1, in <module>
    from .batext import BAText
  File "/usr/local/envs/dict-guided/lib/python3.7/site-packages/AdelaiDet-0.2.0-py3.7-linux-x86_64.egg/adet/modeling/batext/batext.py", line 5, in <module>
    from adet.layers import DFConv2d, IOULoss
  File "/usr/local/envs/dict-guided/lib/python3.7/site-packages/AdelaiDet-0.2.0-py3.7-linux-x86_64.egg/adet/layers/__init__.py", line 1, in <module>
    from .bezier_align import BezierAlign
  File "/usr/local/envs/dict-guided/lib/python3.7/site-packages/AdelaiDet-0.2.0-py3.7-linux-x86_64.egg/adet/layers/bezier_align.py", line 2, in <module>
    from adet import _C
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory
```
I run command by your following:
`python demo/demo.py --config-file configs/BAText/VinText/attn_R_50.yaml --input sample_input/ --output sample_output/ --opts MODEL.WEIGHTS path-to-trained_model-checkpoint`

But had this bug. How to fix this ? Thank you.

**Comment by Al3xDo** [comment]
This command fixed it for me
```
rm -r build
python setup.py develop
```
source: https://github.com/open-mmlab/mmdetection/issues/2627#issuecomment-627884747

**Comment by thongvhoang** [comment]
> This command fixed it for me
> 
> ```
> rm -r build
> python setup.py develop
> ```
> 
> source: [open-mmlab/mmdetection#2627 (comment)](https://github.com/open-mmlab/mmdetection/issues/2627#issuecomment-627884747)
Thank you guys.
