### ISSUE TITLE
cannot import name '_C' from 'adet'

### ISSUE THREAD

**Issue by cuonghv14** [VinAIResearch/dict-guided#9]
Hi guys, 
I'm trying to run your demo on colab. I installed detectron2 and run setup.py as your guide but I have this error:
Traceback (most recent call last):
  File "demo.py", line 10, in <module>
    from adet.config import get_cfg
  File "/content/drive/.shortcut-targets-by-id/1llJY-zZKWqIvj_P5Do1sm_P_no82K__h/VinText/dict-guided/adet/__init__.py", line 1, in <module>
    from adet import modeling
  File "/content/drive/.shortcut-targets-by-id/1llJY-zZKWqIvj_P5Do1sm_P_no82K__h/VinText/dict-guided/adet/modeling/__init__.py", line 3, in <module>
    from .batext import BAText
  File "/content/drive/.shortcut-targets-by-id/1llJY-zZKWqIvj_P5Do1sm_P_no82K__h/VinText/dict-guided/adet/modeling/batext/__init__.py", line 1, in <module>
    from .batext import BAText
  File "/content/drive/.shortcut-targets-by-id/1llJY-zZKWqIvj_P5Do1sm_P_no82K__h/VinText/dict-guided/adet/modeling/batext/batext.py", line 5, in <module>
    from adet.layers import DFConv2d, IOULoss
  File "/content/drive/.shortcut-targets-by-id/1llJY-zZKWqIvj_P5Do1sm_P_no82K__h/VinText/dict-guided/adet/layers/__init__.py", line 1, in <module>
    from .bezier_align import BezierAlign
  File "/content/drive/.shortcut-targets-by-id/1llJY-zZKWqIvj_P5Do1sm_P_no82K__h/VinText/dict-guided/adet/layers/bezier_align.py", line 2, in <module>
    from adet import _C
ImportError: cannot import name '_C' from 'adet' (/content/drive/.shortcut-targets-by-id/1llJY-zZKWqIvj_P5Do1sm_P_no82K__h/VinText/dict-guided/adet/__init__.py)

Can you help me, thank you very much!

**Comment by cuonghv14** [comment]
I got it by run:
!rm -r build
!python setup.py develop
